name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: sg1.fasthost.my.id
          username: luisadha
          port: 1945
          key: ${{ secrets.SSHKEY }}
          script: "cd ~/laras-velvet && ~/.local/bin/deploy"
